# Generated by Django 5.1.7 on 2025-05-13 16:48

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.author')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('qte', models.IntegerField()),
                ('pu', models.FloatField()),
                ('seuil', models.IntegerField()),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur'), ('GERANT', 'Gérant'), ('ADMIN', 'Admin')], default='GERANT', max_length=30)),
                ('delai_livraison', models.DurationField(default=datetime.timedelta(days=3))),
                ('produits', models.ManyToManyField(blank=True, related_name='fournisseurs', to='tpesad.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=30)),
                ('qte', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpesad.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpesad.usertpe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qte', models.IntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREPAREE', 'Preparée'), ('EXPEDIEE', 'Expediée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.produit')),
                ('fournisseur', models.ForeignKey(limit_choices_to={'role': 'FOURNISSEUR'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpesad.usertpe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qte', models.IntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREPAREE', 'Preparée'), ('EXPEDIEE', 'Expediée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.produit')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpesad.usertpe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
