# Generated by Django 5.1.7 on 2025-05-13 22:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('qte', models.IntegerField()),
                ('pu', models.FloatField()),
                ('seuil', models.IntegerField()),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur'), ('GERANT', 'Gérant'), ('ADMIN', 'Admin')], default='GERANT', max_length=30)),
                ('delai_livraison', models.DurationField(default=datetime.timedelta(days=3))),
                ('produits', models.ManyToManyField(blank=True, related_name='fournisseurs', to='tpesad.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=30)),
                ('qte', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpesad.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpesad.usertpe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qte', models.IntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREPAREE', 'Préparée'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.produit')),
                ('fournisseur', models.ForeignKey(limit_choices_to={'role': 'FOURNISSEUR'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpesad.usertpe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qte', models.IntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREPAREE', 'Préparée'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.produit')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpesad.usertpe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
