# Generated by Django 5.1.7 on 2025-04-30 23:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpesad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qte', models.IntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREPAREE', 'Preparée'), ('EXPEDIEE', 'Expediée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.produit')),
                ('userC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qte', models.IntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREPAREE', 'Preparée'), ('EXPEDIEE', 'Expediée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.produit')),
                ('userF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpesad.fournisseur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
