# Generated by Django 5.1.7 on 2025-04-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpesad', '0002_categorie_client_fournisseur_produit_mouvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tpesad.categorie'),
        ),
    ]
