# Generated by Django 5.1.7 on 2025-05-01 00:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpesad', '0002_commandeclient_commandefournisseur_delete_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeclient',
            name='userC',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='userC',
        ),
        migrations.RemoveField(
            model_name='commandefournisseur',
            name='userF',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='userF',
        ),
        migrations.CreateModel(
            name='UserTPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur'), ('GERANT', 'Gérant'), ('ADMIN', 'Admin')], default='GERANT', max_length=30)),
                ('delai_livraison', models.DurationField(default=datetime.timedelta(days=3))),
                ('produits', models.ManyToManyField(blank=True, related_name='fournisseurs', to='tpesad.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpesad.usertpe'),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='fournisseur',
            field=models.ForeignKey(limit_choices_to={'role': 'FOURNISSEUR'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpesad.usertpe'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpesad.usertpe'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
