# Generated by Django 5.1.7 on 2025-04-20 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpesad', '0004_categorie_created_at_categorie_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qte', models.IntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREPAREE', 'Preparée'), ('EXPEDIEE', 'Expediée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], max_length=30)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tpesad.produit')),
                ('userC', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tpesad.client')),
                ('userF', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tpesad.fournisseur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
