# Generated by Django 5.1.7 on 2025-04-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpesad', '0005_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREPAREE', 'Preparée'), ('EXPEDIEE', 'Expediée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='commande',
            name='userC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpesad.client'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='userF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpesad.fournisseur'),
        ),
    ]
