# Generated by Django 5.1.7 on 2025-04-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpesad', '0006_alter_commande_statut_alter_commande_userc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
