# Generated by Django 5.1.7 on 2025-04-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpesad', '0007_commande_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='userC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpesad.client'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='userF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tpesad.fournisseur'),
        ),
    ]
